// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyp7WbmSkENh_C3WqwJL1v3bnsWYlvL2w',
    appId: '1:7093366273:web:61b9ab202cfcc5b20ada00',
    messagingSenderId: '7093366273',
    projectId: 'myfirebase-644c5',
    authDomain: 'myfirebase-644c5.firebaseapp.com',
    storageBucket: 'myfirebase-644c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2rD2FWMED-C5a5ymGflGUGIl5mr3DBR0',
    appId: '1:7093366273:android:314710ec65dde6370ada00',
    messagingSenderId: '7093366273',
    projectId: 'myfirebase-644c5',
    storageBucket: 'myfirebase-644c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANXp0VdtA6H8WJvGO6yB1V7ywr5f9S5q8',
    appId: '1:7093366273:ios:778e3901a735478d0ada00',
    messagingSenderId: '7093366273',
    projectId: 'myfirebase-644c5',
    storageBucket: 'myfirebase-644c5.appspot.com',
    iosBundleId: 'com.example.myfirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANXp0VdtA6H8WJvGO6yB1V7ywr5f9S5q8',
    appId: '1:7093366273:ios:9e24df4a68ed294c0ada00',
    messagingSenderId: '7093366273',
    projectId: 'myfirebase-644c5',
    storageBucket: 'myfirebase-644c5.appspot.com',
    iosBundleId: 'com.example.myfirebaseapp.RunnerTests',
  );
}
